baseURL: "https://vicu.sgcomp-tech.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "VICU"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "VICU"
  description: "We provide secure door access system. Integrated to our system, we can connect to your IOTs and interface to third party system for seamless office automation and monitoring."
  images: 
    - "images/hero-image.png"

  logo: "images/logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "57 Ubi Ave 1 #07-07, Singapore 408936"

  contact:
    - "support@sgcomp-tech.com"
    - "6841 0951"

  copyright: "© 2022 SG Comp-Tech Pte Ltd"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Pricing"
      url: "/#"
      weight: 2

    - name: "Blog"
      url: "/blog"
      weight: 3

  buttons:
    - name: "Contact us"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Pricing"
      url: "/#"
      weight: 2

    - name: "Blog"
      url: "/blog"
      weight: 3

taxonomies:
  series: "series"
  tags: "tags"
